services:
  db:
    container_name: postgres-database
    image: postgres:15-alpine
    volumes:
      # - postgres-db:/var/lib/postgresql/data  #ejemplo
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=omar@test.com
# volumes:
#   postgres-db:
#     external: true
